"""Add analyze page fields to profiles

Revision ID: c103b903b699
Revises: 005_add_analyze_page_fields
Create Date: 2025-09-17 21:50:06.413936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c103b903b699'
down_revision = '005_add_analyze_page_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('desired_role', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('career_goals', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('timeframe', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('salary_expectation', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('education', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('certifications', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('languages', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('work_type', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('company_size', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('work_culture', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('benefits', sa.JSON(), nullable=True, comment='Preferred benefits as JSON array'))
    op.add_column('user_profiles', sa.Column('profile_score', sa.Float(), nullable=True, comment='Overall profile score (0-100)'))
    op.add_column('user_profiles', sa.Column('completeness_score', sa.Float(), nullable=True, comment='Profile completeness score (0-100)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'completeness_score')
    op.drop_column('user_profiles', 'profile_score')
    op.drop_column('user_profiles', 'benefits')
    op.drop_column('user_profiles', 'work_culture')
    op.drop_column('user_profiles', 'company_size')
    op.drop_column('user_profiles', 'work_type')
    op.drop_column('user_profiles', 'languages')
    op.drop_column('user_profiles', 'certifications')
    op.drop_column('user_profiles', 'education')
    op.drop_column('user_profiles', 'salary_expectation')
    op.drop_column('user_profiles', 'timeframe')
    op.drop_column('user_profiles', 'career_goals')
    op.drop_column('user_profiles', 'desired_role')
    op.drop_column('user_profiles', 'industry')
    # ### end Alembic commands ###